import pyautogui,time

time.sleep(1)
pyautogui.click(x=1341, y = 270, clicks = 1)
pyautogui.click(x=192, y = 51, clicks = 1)
pyautogui.typewrite("https://forms.office.com/r/S8Jy6Jsvmh")
pyautogui.press('enter')

time.sleep(2)
pyautogui.click(x=308, y = 443, clicks = 1)
time.sleep(2)
pyautogui.click(x=327, y = 707, clicks = 1)
#input()
pyautogui.typewrite("Somos una imposibilidad en un universo imposible.   Ray Bradbury")
time.sleep(1)
pyautogui.press('tab')
pyautogui.press('tab')

pyautogui.press('enter')
pyautogui.click(x=372, y = 626, clicks = 1)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite("“Falso")
pyautogui.hotkey('shift','2')#@
pyautogui.typewrite("Falso.com")
pyautogui.press('tab')
pyautogui.press('enter')

time.sleep(1)
pyautogui.press('f5')
time.sleep(1)
pyautogui.click(x=308, y = 525, clicks = 1)
time.sleep(2)
pyautogui.click(x=327, y = 707, clicks = 1)
#input()
pyautogui.typewrite("Tú creas el mundo del sueño. Nosotros llevamos al sujeto a ese sueño y él lo llena con su subconsciente.")
time.sleep(1)
pyautogui.press('tab')
pyautogui.press('tab')

pyautogui.press('enter')
pyautogui.click(x=375, y = 655, clicks = 1)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite("“Falso123")
pyautogui.hotkey('shift','2')#@
pyautogui.typewrite("Falso.com")
pyautogui.press('tab')
pyautogui.press('enter')